# Generated by Django 5.0.2 on 2024-02-26 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, verbose_name='TIPO')),
                ('marca', models.CharField(max_length=20, verbose_name='MARCA')),
                ('modelo', models.CharField(max_length=15, verbose_name='MODELO')),
                ('serial', models.CharField(max_length=15, unique=True, verbose_name='SERIAL')),
                ('estado', models.BooleanField(choices=[(True, 'Bueno'), (False, 'Falla')], null=True, verbose_name='ESTADO ACTUAL DEL EQUIPO')),
                ('registro_entrada', models.BooleanField(choices=[(True, 'SI (WIP)'), (False, 'NO (WIP)')], null=True, verbose_name='Registro Fotografico Entrada')),
                ('registro_salida', models.BooleanField(choices=[(True, 'SI (WIP)'), (False, 'NO (WIP)')], null=True, verbose_name='Registro Fotografico Salida')),
                ('sistema_operativo', models.CharField(max_length=15, verbose_name='SISTEMA OPERATIVO INSTALADO')),
                ('estado_hdd', models.BooleanField(choices=[(True, 'Bueno'), (False, 'Malo')], null=True, verbose_name='ESTADO DISCO DURO')),
                ('ram', models.CharField(max_length=10, verbose_name='RAM ACTUAL')),
                ('tipo_procesador', models.CharField(max_length=15, verbose_name='TIPO PROCESADOR')),
                ('estado_fisico', models.TextField(blank=True, verbose_name='ESTADO FISICO')),
                ('siniestro', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='SINIESTRO')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_tool', models.BooleanField(choices=[(True, 'Bueno'), (False, 'Falla')], null=True, verbose_name='En Laptops LENOVO Ejecutar Lenovo Diagnostics Tool sobre todos los componentes')),
                ('diag_tool_desc', models.TextField(blank=True, verbose_name='¿Que esta fallando?')),
                ('upd_bios', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='Actualizacion de BIOS')),
                ('upd_bios_ver', models.CharField(max_length=15, verbose_name='Version BIOS')),
                ('upd_bios_desc', models.TextField(blank=True, verbose_name='Observaciones actualizacion BIOS')),
                ('upd_all', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='Actualizacion Drivers al dia')),
                ('upd_all_desc', models.TextField(blank=True, verbose_name='¿Por que?')),
                ('upd_audio', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Audio')),
                ('upd_video', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Video')),
                ('upd_wifi', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Red WIFI')),
                ('upd_ethernet', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Red Ethernet')),
                ('upd_almacenamiento', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Dispositivos almacenamiento')),
                ('upd_chipset', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Chipset')),
                ('upd_camara', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Camara')),
                ('upd_mouse', models.BooleanField(choices=[(True, 'Aplica'), (False, 'No Aplica')], null=True, verbose_name='Mouse')),
                ('exe_all', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='¿Se ejecutaron todos los Drivers?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones actualizacion Drivers')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teclado', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Teclado')),
                ('pantalla', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Pantalla (Brillo)')),
                ('sonido', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Sonido (Altavoz)')),
                ('camara', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Camara')),
                ('touchpad', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='TouchPad')),
                ('wifi', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Interfaz de red WIFI/RJ45')),
                ('video_hdmi_vga', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Video/HDMI/VGA')),
                ('internet', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Acceso a Internet')),
                ('apps_cliente', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='Acceso aplicativos cliente')),
                ('headset', models.BooleanField(choices=[(True, 'Funciona'), (False, 'No Funciona')], null=True, verbose_name='HeadSet (Diadema)/Microfono')),
                ('limpieza', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='Limpieza fisica interna y externa')),
                ('funciona', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='¿Funcionamiento correcto despues de la intervencion?')),
                ('funciona_desc', models.TextField(blank=True, verbose_name='¿Por que?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_office', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='VALIDAR DESACELERACION GRAFICA DE OFFICE 365')),
                ('des_chrome', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='VALIDAR DESACELERACION GRAFICA DE GOOGLE CHROME')),
                ('des_teams', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='VALIDAR DESACELERACION GRAFICA DE MICROSOFT TEAMS')),
                ('del_temp', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='ELIMINAR TEMPORALES DE WINDOWS (TEMP)')),
                ('dfg_dd', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='DESFRAGMENTAR EL DISCO (ANALIZAR - OPTIMIZAR) HDD-SSD')),
                ('del_temp2', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='ELIMINAR TEMPORALES OCULTOS DE USUARIO (%TEMP%)')),
                ('del_prefetch', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='ELIMINAR ARCHIVOS CACHE DE WINDOWS EN CARPETA PREFETCH')),
                ('conf_msconfig', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='CONFIGURACION DEL MSCONFIG (15 segundos de Tiempo de Arranque)')),
                ('sfc_scannow', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='SFC / SCANNOW (ejecutar como administrador en Power Shell)')),
                ('win_22h2', models.BooleanField(choices=[(True, 'SI'), (False, 'NO')], null=True, verbose_name='22H2 ULTIMA COMPILACION WINDOWS 10 (19045.3271-3374)')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='NOMBRE USUARIO FINAL')),
                ('fecha_intervencion', models.DateField(null=True, verbose_name='FECHA INTERVENCIÓN')),
                ('ciudad', models.CharField(max_length=50, verbose_name='CIUDAD')),
                ('telefono', models.CharField(max_length=10, verbose_name='TELEFONO CONTACTO')),
                ('usuario_red', models.CharField(max_length=50, verbose_name='USUARIO DE RED, CLAVE DE USUARIO')),
                ('activo', models.CharField(max_length=20, verbose_name='ACTIVO')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo')),
            ],
        ),
    ]
